language: java
jdk:
  - openjdk6

env:
  global:
    - SONATYPE_USERNAME=culturegraph
    - secure:"QnSKDizDP3OgVyC4gcNACKKxIuwg3pht+2qU8SonpOQgQ7E7Y0a7XBSxndfaEUGKgodhepjDcn2TCgU0dxXgY7ueAUByOcA2rM   38AVvm9not5EuXFkl4gue4cBUv+LQLZzM/51Hl272FwETbZDLNyb1l+fR8RNftKMxrVXPfaq0="



after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { python travis-ci/configure-mvn.py ; mvn clean deploy --settings ~/.m2/mySettings.xml -Dgpg.skip=true -Psonatype-oss-release ; }"
